### ISSUE TITLE
Update Assets for Dark Theme Compatibility

### ISSUE THREAD

**Issue by DBozhinovski** [Dxmentorship/dxmentorship#18]
As we transition to using the Navy template, which features a dark theme, it's imperative that we update our existing assets to ensure they are visually appealing and legible in a dark-themed environment. This includes updating images, icons, and any other graphical elements used across our site.

- [ ] Review all existing assets on our pages
- [ ] Identify assets that may not be suitable for a dark theme and list them.
- [ ] Source or create new versions of these assets that are designed to work well with a dark theme (See resources below for some recommendations).
- [ ] Replace the old assets with the new, dark-theme-friendly assets on our Astro pages. Try using [Astro images](https://docs.astro.build/en/guides/images/#images-in-astro-files) where it makes sense (since it auto-optimizes them).

Asset resources (just suggestions, feel free to use other sources):

https://openpeeps.com/
https://undraw.co/illustrations
https://iconduck.com/
https://www.svgrepo.com/
https://iconoir.com/
https://www.humaaans.com/
https://icons8.com/illustrations
https://blush.design/
https://www.drawkit.com/
https://absurd.design/
https://lukaszadam.com/illustrations

**Comment by CBID2** [comment]
Hi there @DBozhinovski. Does this issue still need solving? I’m willing to give it a try :)

**Comment by DBozhinovski** [comment]
@CBID2 I think we can close it, because the site already got deployed with some updates. Feel free to suggest some improvements tho!

**Comment by CBID2** [comment]
> @CBID2 I think we can close it, because the site already got deployed with some updates. Feel free to suggest some improvements tho!

Ok I'll close it :)
