### ISSUE TITLE
Submit Graduate Data for the Graduates Page

### ISSUE THREAD

**Issue by DBozhinovski** [Dxmentorship/dxmentorship#19]
We are transitioning from using Notion to a more robust solution for showcasing our graduates on the Graduates page. To achieve this, we need each graduate of the DXMentorship program to submit their data through a Pull Request (PR) to our repository.

---

Template:

```
---
name: Your Full Name
graduation_cohort: XX
portfolio_url: http://your-portfolio.com
blog_url: http://your-blog.com
personal_site: http://your-site.com
linkedin_url: http://linkedin.com/in/your-profile
github_url: http://github.com/your-profile
---

A short bio about yourself. Talk about your journey, what you learned from the DXMentorship program, and your goals for the future.

```

---

Using this template, please submit an updated version of what we had in Notion, see that we can use it in our new DXMentorship page.

**Comment by DBozhinovski** [comment]
Assigning myself so that I migrate the Notion logic to an Astro-generated pages from the data. Otherwise, everyone submitting should refer this issue in the PR.

**Comment by kohasummons** [comment]
Completed. ✅
