### ISSUE TITLE
Migrate Page: Curriculum

### ISSUE THREAD

**Issue by kohasummons** [Dxmentorship/dxmentorship#21]
Migrate the Curriculum page route from the Next.js version to an Astro route, utilizing the new template structure. Match the style and layout to the [Method home](https://navy.lexingtonthemes.com/method-home) from the template.

Acceptance Criteria:
- [ ] Curriculum page has been migrated to an Astro route and styled according to the new template.
- [ ] All existing functionalities are working as expected.
- [ ] Documentation updated to reflect the new route structure.

**Comment by DesmondSanctity** [comment]
I want to work on this. @kohasummons

**Comment by kohasummons** [comment]
Brilliant choice, man.

**Comment by kohasummons** [comment]
[The Theme](https://lexingtonthemes.com/)

**Comment by kohasummons** [comment]
Now up-for-grabs. @kenny-io do you wanna take this?
