### ISSUE TITLE
Add a Contributing.md file

### ISSUE THREAD

**Issue by Charity10** [Dxmentorship/dxmentorship#27]
Open source projects should include a CONTRIBUTING.md file to provide guidelines for contributions and make it easier for users to understand how to contribute effectively.
If this issue is accepted, I'd like for it to be assigned to me and also be provided with the necessary information I need to create a contributing.md file for this project.

**Comment by Charity10** [comment]
Thank you @kohasummons 
This is my first time opening an issue, am I the one to add a label to the issue? 
I don't seem to see the option to add a label from my end.
I wanted to add the hacktoberfest label to this issue

**Comment by kohasummons** [comment]
Hi @Charity10. We already have the 'hacktoberfest' topic added to the repository so all PRs once merge fufill the hacktoberfest requirements.
